backend:
  name: git-gateway
  branch: master
media_folder: "images/posts"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Description", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Comments", name: "comments", widget: "hidden", default: "true"}
  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About Page"
        file: "_pages/about.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "data"
    label: "Data"
    files:
      - name: "videoslist"
        label: "Videos"
        file: "_data/videos.yaml"
        fields:
          - name: "videos"
            label: "Videos"
            widget: list
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "URL", name: "URL", widget: "string"}
      - name: "pubslist"
        label: "Publications"
        file: "_data/publications.yaml"
        fields:
          - name: "publications"
            label: "Publications"
            widget: list
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - name: "articles"
                label: "articles"
                widget: list
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "URL", name: "URL", widget: "string"}
      - name: "presoslist"
        label: "Presentations"
        file: "_data/presentations.yaml"
        fields:
          - name: "presentations"
            label: "Presentations"
            widget: list
            fields:
              - {label: "Month Year", name: "name", widget: "string"}
              - name: "presentations"
                label: "Presentations"
                widget: list
                fields:
                  - {label: "Title", name: "title", widget: "string"}